### PR TITLE
Rewrite to use node:http instead of express, and more options

### PR DESCRIPTION
**Pull request by KraXen72**
Hi, i stumbled upon your adapter for IIS, and while it was a good start, it was not working that well for me.
I modified it pretty extensively, adding features i needed. I thought it might be a good idea to contribute them back, since you said contributions are welcome in the readme.

## Differences
- use `node:http` server instead of `express`, so it does not require an external dependency of `express`
- add environment variables to `web.config`, to pass to `iisnode`. Gets POST requests, form actions to work, instead of throwing error 403
- `getClientAddress` now works again, using the `x-forwarded-for` header and iisnode's `enableXFF="true"`
- added `outputWhitelist` option: a whitelist array to not be deleted from `.svelte-kit/adapter-iis` during build (explained in readme)
- added `externalRoutes` option: allow some routes to be not rewritten to sveltekit, for example, for Virtual Directories support
- added `externalRoutesIgnoreCase` option: controls case sensitiveness of these routes
- added `healthcheckRoute` option: a simple `/healthcheck` route for debuging while setting up IIS
- rewrote the readme pretty extensibly, including a troubleshooting section for people who aren't that familiar with IIS.
- better types for the options, extended `adapter-node`'s option interface

The biggest switch is from using `express` to `node:http`. While they aren't completely the same, it has worked for all my use-cases, and i haven't noticed any differences. My motivation behind the switch is: 
- unless the app has runtime dependencies, you shouldn't `npm/yarn/pnpm install` on the build output, and rather use devDependencies, which if imported, are packaged. Introducing a runtime dependency unnecessarily complicates the build & update process.
- adding the external dependency of express and installing it there or globally is really cumbersome and adds friction

Please let me know any requested changes.

### CODE REVIEW

**Comment by abaga129** [comment]
@KraXen72 Sorry I didnt see your PR sooner.  This all looks great.  I'm going to look everything over and test it a bit but I dont see any reason not to merge this as it seems to be a major improvement!

**Comment by KraXen72** [comment]
thanks for merging! i'll likely contribute some more stuff in the future :3

**Comment by abaga129** [comment]
That sounds great! Thank you for this big contribution.  I went ahead and squashed the commits into a single commit just to clean up the git history.  I hope that's okay.  So you will need to updated your fork before making another PR.

I'm glad to see we can work together on IIS support for Sveltekit!

**Comment by abaga129** [comment]
Also @KraXen72 I've tagged v1.1.0 so you should be able to install it from the npm registry now

**Comment by KraXen72** [comment]
sure, great!

**Pull request merged**
