### PR TITLE
Change dependencies to dev dependencies

### PR DESCRIPTION
**Pull request by abaga129**
@Palkess @KraXen72 I think these dependencies should have been dev dependencies when the project was initially created.  Thoughts?

### CODE REVIEW

**Comment by Palkess** [comment]
I think this looks good, none of the deps should be required during production 👍

**Comment by KraXen72** [comment]
doesen't sveltekit bundle all of devdependencies though?

**Comment by KraXen72** [comment]
i don't think they should be in dev-dependencies if they're requried for the runtime though, no? like we import and use functions from fs-extra, if it's not a dependency, won't it get ommited when installing?
you could take a look at how adapter-node does it

**Comment by Palkess** [comment]
I think you're right @KraXen72 , I was probably thinking from the perspective of a repo using this npm package as a devDep. This could always be tested if you want to set up a way to do beta-releases in npm @abaga129 .

**Comment by abaga129** [comment]
Hmm yes I see your point. I'll read into it a bit more.  It does look like our sveltekit dependency should atleast be a peer dependency.

**Pull request closed without merging**
